package model;

import java.util.ArrayList;
import java.util.List;

public class Admin extends User {
    private int adminLevel;

    public Admin(String id, String name, String email, String mobile,
                 String username, String passwordHash, int adminLevel) {
        super(id, name, email, mobile, username, passwordHash, UserRole.ADMIN);
        this.adminLevel = adminLevel;
    }

    // Admin-specific methods from UML
    public boolean addUser(User user) {
        System.out.println("Admin " + getName() + " added user: " + user.getName());
        return true;
    }

    public boolean deleteUser(String userId) {
        System.out.println("Admin " + getName() + " deleted user ID: " + userId);
        return true;
    }

    public boolean updateUser(User user) {
        System.out.println("Admin " + getName() + " updated user: " + user.getName());
        return true;
    }

    public User viewUser(String userId) {
        System.out.println("Admin " + getName() + " viewing user ID: " + userId);
        // In real app, this would fetch from database
        return null;
    }

    public List<User> viewAllUsers() {
        System.out.println("Admin " + getName() + " viewing all users");
        return new ArrayList<>();
    }

    public String generateReport() {
        return "System Report generated by Admin: " + getName() +
                " (Level: " + adminLevel + ")";
    }

    // Getter and Setter
    public int getAdminLevel() { return adminLevel; }
    public void setAdminLevel(int adminLevel) { this.adminLevel = adminLevel; }
}